### ISSUE TITLE
Wrong class instance

### ISSUE THREAD

**Issue by SarloAkrobata** [Kludex/fastapi-microservices#72]
https://github.com/Kludex/fastapi-microservices/blob/cee0a7df02377c9980ecf4fc41e321e96e41c8d9/users/app/crud/users.py#L6

It should be like this:
crud_user = CRUDUser(User)

Also I think better way would be like this, because it makes open for extendibility (eg. write or overwrite specific queries, the features of repository pattern):

```from app.crud.base import CRUDBase
from app.models.users import User
from app.schemas.user import UserInDB, UserUpdateDB

class CRUDUser(CRUDBase[User, UserInDB, UserUpdateDB]):
    pass

crud_user = CRUDUser(User)

**Comment by Kludex** [comment]
PR welcome.

**Comment by Kludex** [comment]
This was solved already. 👍
